steps:
  - name: build-dry-run
    image: woodpeckerci/plugin-kaniko:2.1.0
    settings:
      dry-run: true
      repo: mirkodinc
      tags: git-${CI_COMMIT_SHA:0:4}
      dockerfile: Dockerfile
    when:
      - event: [pull_request]
        branch:
          exclude: main
  - name: publish
    image: woodpeckerci/plugin-kaniko:2.1.0
    settings:
      repo: mirkodinc
      tags: git-${CI_COMMIT_SHA:0:4}
      dockerfile: Dockerfile
      registry: registry.rojandinc.se
      insecure: true
    when:
      - event: [push]
        branch: [main]
  - name: deploy
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      namespace: mirko
      chart: rojandinc/web
      chart_version: 0.1.0
      add_repos: ["rojandinc=https://rojandinc.github.io/helm-charts"]
      release: mirkodinc
      skip_tls_verify: true
      values: "image.tag=git-${CI_COMMIT_SHA:0:4}"
      values_files:
        - "environment/values.yaml"
      api_server: https://kubernetes.default
      kubernetes_token:
        from_secret: kubernetes_token
    depends_on: [publish]
    when:
      - event: [push]
        branch: [main]
