image:
  repository: registry.home/mirkodinc
  tag: latest
ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: tunnel.rojandinc.se
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: mirko.rojandinc.se
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mirko-tls
      hosts:
        - mirko.rojandinc.se
service:
  port: 80
resources:
  requests:
    cpu: 10m
    memory: 64Mi
autoscaling:
  enabled: false
